// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://harushcedavxjtjqsxya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhcnVzaGNlZGF2eGp0anFzeHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDExMDksImV4cCI6MjA2OTgxNzEwOX0.kJ1w5Y2sTUq1COZJ2O6HF3Ulrf6iymkZ84GE2IVFdsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});